Setup CircleCI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,26 +1,238 @@
 version: 2.1
 
+commands:
+  setup_sbt:
+    description: Get and install SBT
+    parameters:
+      sbt_version:
+        type: string
+        default: "1.3.9"
+    steps:
+      - restore_cache:
+          keys:
+          - sbt-{{ checksum "project/build.properties" }}
+
+      - run:
+          name: Setup SBT
+          command: |
+                    if [ ! -x ~/sbt/bin/sbt ]; then
+                      cd ~/
+                      curl --silent -L -o sbt.tgz https://piccolo.link/sbt-<< parameters.sbt_version >>.tgz
+                      tar -xzvf sbt.tgz && rm -f sbt.tgz
+                    fi
+
+      - save_cache:
+          paths:
+            - ~/sbt
+          key: sbt-{{ checksum "project/build.properties" }}
+
+  setup_integration:
+    description: Setup integration environment
+    steps:
+      - restore_cache:
+          keys:
+          - mongodb-{{ checksum ".ci_scripts/beforeInstall.sh" }}
+
+      - run:
+          name: Prepare integration environment
+          command: |
+                    if [ `which make | wc -l` -eq 0 ]; then
+                      sudo apt update
+                      sudo apt install build-essential
+                    fi
+                    ./.ci_scripts/beforeInstall.sh
+
+      - save_cache:
+          paths:
+            - ~/ssl
+            - ~/mongodb-linux-x86_64-amazon-3.6.6
+          key: mongodb-{{ checksum ".ci_scripts/beforeInstall.sh" }}
+
+      - run:
+          name: Start integration services
+          command: |
+                    export MONGO_CONF="/tmp/mongod.conf"
+                    ./.ci_scripts/fork-mongod.sh /tmp/validate-env.sh
+          background: true
+
+  build_n_tests:
+    description: Build & Run tests
+    steps:
+      - restore_cache:
+          keys:
+          - scala-{{ .Environment.CIRCLE_JOB }}-{{ checksum "build.sbt" }}-{{ checksum "project/Common.scala" }}
+
+      - run:
+          name: Build & Run tests
+          command: |
+                    export PATH=$PATH:~/sbt/bin
+                    export USER=`basename $HOME`
+                    
+                    ./.ci_scripts/validate.sh
+
+      - save_cache:
+          paths:
+            - ~/.ivy2
+            - ~/.coursier/cache
+            - ~/.sbt
+          key: scala-{{ .Environment.CIRCLE_JOB }}-{{ checksum "build.sbt" }}-{{ checksum "project/Common.scala" }}
+
+
+  collect_test_reports:
+    description: Collect test reports
+    steps:
+      - run:
+          name: Collect test report
+          command: |
+                    mkdir test-reports
+                    find . -path '*/test-reports/*' -name '*.xml' \
+                      -print -exec cp {} test-reports \;
+          when: always
+
+  publish_snapshots:
+    description: Publish artifacts to Snapshots repository
+    parameters:
+      release_suffix:
+        type: string
+        default: ""
+      play_version:
+        type: string
+        default: ""
+      scala_versions:
+        type: string
+        default: ""
+    steps:
+      - deploy:
+          name: Publish artifacts to Sonatype Snapshots
+          command: |
+                    if [ ! "${CIRCLE_BRANCH}" = "master" ]; then
+                      echo "Skipped on branch ${CIRCLE_BRANCH}"
+                      exit 0
+                    fi
+                    
+                    export PUBLISH_REPO_NAME="Sonatype Nexus Repository Manager"
+                    export PUBLISH_REPO_ID="oss.sonatype.org"
+                    export PUBLISH_REPO_URL="https://oss.sonatype.org/content/repositories/snapshots"
+                    
+                    if [ "x$PUBLISH_USER" = "x" -o "x$PUBLISH_PASS" = "x" ]; then
+                      echo "Missing publication credentials"
+                      exit 1
+                    fi
+                    
+                    export RELEASE_SUFFIX="<< parameters.release_suffix >>"
+                    export PLAY_VERSION="<< parameters.play_version >>"
+                    
+                    echo "Publishing artifacts for $PLAY_VERSION"
+                    
+                    if [ "x<< parameters.scala_versions >>" = "x" ]; then
+                      sbt +publish
+                    else
+                      for V in `echo "<< parameters.scala_versions >>"`; do
+                        sbt ++$V publish
+                      done
+                    fi
+
 jobs:
-  scala211_akka24:
+  jdk8_scala212_play26:
     docker:
       - image: circleci/openjdk:8-jdk
 
     working_directory: ~/repo
 
     environment:
-      AKKA_VERSION: 2.4.10
-      ITERATEES_VERSION: 2.3.10
       REACTIVEMONGO_SHADED: false
-      SCALA_VERSION: 2.11.12
+      RELEASE_SUFFIX: play26
+      PLAY_VERSION: 2.6.7
+      SCALA_VERSION: 2.12.10
     
     steps:
       - checkout
+      - setup_sbt
+      - setup_integration
+      - build_n_tests
+      - collect_test_reports
       - store_test_results:
           path: test-reports
+
+  jdk9_scala213_play27:
+    docker:
+      - image: circleci/openjdk:9-jdk
+
+    working_directory: ~/repo
+
+    environment:
+      RELEASE_SUFFIX: play27
+      PLAY_VERSION: 2.7.4
+      SCALA_VERSION: 2.13.1
+    
+    steps:
+      - checkout
+      - setup_sbt
+      - setup_integration
+      - build_n_tests
+      - collect_test_reports
+      - store_test_results:
+          path: test-reports
+
+  jdk10_scala213_play28:
+    docker:
+      - image: circleci/openjdk:10-jdk
+
+    working_directory: ~/repo
+
+    environment:
+      RELEASE_SUFFIX: play28
+      PLAY_VERSION: 2.8.1
+      SCALA_VERSION: 2.13.1
+    
+    steps:
+      - checkout
+      - setup_sbt
+      - setup_integration
+      - build_n_tests
+      - collect_test_reports
+      - store_test_results:
+          path: test-reports
+
+  publish_snapshots:
+    docker:
+      - image: circleci/openjdk:8-jdk
+
+    working_directory: ~/repo
+    
+    steps:
+      - checkout
+      - setup_sbt
+
+      - publish_snapshots:
+          release_suffix: play25
+          play_version: 2.5.7
+          scala_versions: 2.11.12
+
+      - publish_snapshots:
+          release_suffix: play26
+          play_version: 2.6.7
+          scala_versions: 2.11.12 2.12.10
+
+      - publish_snapshots:
+          release_suffix: play27
+          play_version: 2.7.3
+
+      - publish_snapshots:
+          release_suffix: play28
+          play_version: 2.8.0
+          scala_versions: 2.12.10 2.13.1
 
 workflows:
   version: 2
 
   main_suite:
     jobs:
-      - scala211_akka24
+      - jdk8_scala212_play26
+      - jdk9_scala213_play27
+      - jdk10_scala213_play28
+      - publish_snapshots:
+          requires:
+            - jdk8_scala212_play26
+            - jdk9_scala213_play27
+            - jdk10_scala213_play28
