Update to SBT 2.0.1

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,7 +6,7 @@ commands:
     parameters:
       sbt_version:
         type: string
-        default: "1.11.4"
+        default: "2.0.1"
     steps:
       - restore_cache:
           keys:
@@ -105,22 +105,23 @@ commands:
                       echo "Skipped on branch ${CIRCLE_BRANCH}"
                       exit 0
                     fi
-                    V=`sbt -J-Dsbt.log.noformat=true 'show version' 2>&1 | tail -n 2 | cut -d ']' -f 2 | grep SNAPSHOT | sed -e 's/[ \t]*//g'`
-                    if [ `echo "$V" | grep -- '-SNAPSHOT' | wc -l` -eq 0 ]; then
-                      S=`echo "$V" | perl -pe 's/([0-9]+)$/${\($1 + 1)}-SNAPSHOT/'`
-                      echo "Cannot bump $V to $S"
-                      echo "ThisBuild / version := \"$S\"" > version.sbt
+
+                    if [ "x$PUBLISH_USER" = "x" -o "x$PUBLISH_PASS" = "x" ]; then
+                      echo "Missing publication credentials"
+                      exit 1
+                    fi
+
+                    V=$(sbt --server 'show version' 2>&1 | sed 's/\x1b\[0[Jm]//g' | grep --color=never '[0-9]\+\.[0-9]\+' | tail -1 | sed 's/\[info\]//' | xargs | tr -cd '[:alnum:]._-')
+
+                    if [[ "$V" != *SNAPSHOT* ]]; then
+                      echo "Skip non snapshot: $V"
+                      exit 0
                     fi
 
                     export PUBLISH_REPO_NAME="Sonatype Nexus Repository Manager"
                     export PUBLISH_REPO_ID="central.sonatype.com"
                     export PUBLISH_REPO_URL="https://central.sonatype.com/repository/maven-snapshots/"
-                    
-                    if [ "x$PUBLISH_USER" = "x" -o "x$PUBLISH_PASS" = "x" ]; then
-                      echo "Missing publication credentials"
-                      exit 1
-                    fi
-                    
+                   
                     export RELEASE_SUFFIX="<< parameters.release_suffix >>"
                     export PLAY_VERSION="<< parameters.play_version >>"
                     
@@ -135,9 +136,9 @@ commands:
                     fi
 
 jobs:
-  jdk8_scala212_play26:
+  jdk26_scala212_play26:
     docker:
-      - image: cimg/openjdk:8.0
+      - image: cimg/openjdk:26.0
 
     working_directory: ~/repo
 
@@ -145,7 +146,7 @@ jobs:
       REACTIVEMONGO_SHADED: false
       RELEASE_SUFFIX: play26
       PLAY_VERSION: 2.6.7
-      SCALA_VERSION: 2.12.20
+      SCALA_VERSION: '2.12'
     
     steps:
       - checkout
@@ -156,16 +157,16 @@ jobs:
       - store_test_results:
           path: test-reports
 
-  jdk10_scala213_play27:
+  jdk17_scala213_play27:
     docker:
-      - image: cchantep/circleci-openjdk:10-jdk
+      - image: cimg/openjdk:17.0
 
     working_directory: ~/repo
 
     environment:
       RELEASE_SUFFIX: play27
       PLAY_VERSION: 2.7.4
-      SCALA_VERSION: 2.13.17
+      SCALA_VERSION: '2.13'
     
     steps:
       - checkout
@@ -176,16 +177,16 @@ jobs:
       - store_test_results:
           path: test-reports
 
-  jdk11_scala213_play28:
+  jdk26_scala213_play28:
     docker:
-      - image: cchantep/circleci-openjdk:11-jdk
+      - image: cimg/openjdk:26.0
 
     working_directory: ~/repo
 
     environment:
       RELEASE_SUFFIX: play28
       PLAY_VERSION: 2.8.22
-      SCALA_VERSION: 2.13.17
+      SCALA_VERSION: '2.13'
     
     steps:
       - checkout
@@ -196,16 +197,16 @@ jobs:
       - store_test_results:
           path: test-reports
 
-  jdk11_scala213_play29:
+  jdk17_scala213_play29:
     docker:
-      - image: cchantep/circleci-openjdk:11-jdk
+      - image: cimg/openjdk:17.0
 
     working_directory: ~/repo
 
     environment:
       RELEASE_SUFFIX: play29
       PLAY_VERSION: 2.9.1
-      SCALA_VERSION: 2.13.17
+      SCALA_VERSION: '2.13'
 
     steps:
       - checkout
@@ -216,16 +217,16 @@ jobs:
       - store_test_results:
           path: test-reports
 
-  jdk11_scala213_play30:
+  jdk26_scala213_play30:
     docker:
-      - image: cchantep/circleci-openjdk:11-jdk
+      - image: cimg/openjdk:26.0
 
     working_directory: ~/repo
 
     environment:
       RELEASE_SUFFIX: play30
       PLAY_VERSION: 3.0.4
-      SCALA_VERSION: 2.13.17
+      SCALA_VERSION: '2.13'
 
     steps:
       - checkout
@@ -236,9 +237,9 @@ jobs:
       - store_test_results:
           path: test-reports
 
-  jdk11_scala3_play30:
+  jdk17_scala3_play30:
     docker:
-      - image: cchantep/circleci-openjdk:11-jdk
+      - image: cimg/openjdk:17.0
 
     working_directory: ~/repo
 
@@ -299,7 +300,7 @@ jobs:
       - publish_snapshots:
           release_suffix: play26
           play_version: 2.6.7
-          scala_versions: 2.11.12 2.12.20
+          scala_versions: 2.11 2.12
 
       - save_cache:
           paths:
@@ -325,7 +326,7 @@ jobs:
       - publish_snapshots:
           release_suffix: play27
           play_version: 2.7.3
-          scala_versions: 2.12.20 2.13.17
+          scala_versions: 2.12 2.13
 
       - save_cache:
           paths:
@@ -351,7 +352,7 @@ jobs:
       - publish_snapshots:
           release_suffix: play28
           play_version: 2.8.1
-          scala_versions: 2.12.20 2.13.17
+          scala_versions: 2.12 2.13
 
       - save_cache:
           paths:
@@ -377,7 +378,7 @@ jobs:
       - publish_snapshots:
           release_suffix: play29
           play_version: 2.9.1
-          scala_versions: 2.13.17
+          scala_versions: '2.13'
 
       - save_cache:
           paths:
@@ -403,7 +404,7 @@ jobs:
       - publish_snapshots:
           release_suffix: play30
           play_version: 3.0.4
-          scala_versions: 2.13.17 3.3
+          scala_versions: 2.13 3.3
 
       - save_cache:
           paths:
@@ -428,12 +429,12 @@ workflows:
 
   main_suite:
     jobs:
-      - jdk8_scala212_play26
-      - jdk10_scala213_play27
-      - jdk11_scala213_play28
-      - jdk11_scala213_play29
-      - jdk11_scala213_play30
-      - jdk11_scala3_play30
+      - jdk26_scala212_play26
+      - jdk17_scala213_play27
+      - jdk26_scala213_play28
+      - jdk17_scala213_play29
+      - jdk26_scala213_play30
+      - jdk17_scala3_play30
 
       - publish_snapshots_play25_scala211:
           filters:
@@ -441,12 +442,12 @@ workflows:
               only:
                 - master
           requires:
-            - jdk8_scala212_play26
-            - jdk10_scala213_play27
-            - jdk11_scala213_play28
-            - jdk11_scala213_play29
-            - jdk11_scala3_play30
-            - jdk11_scala213_play30
+            - jdk26_scala212_play26
+            - jdk17_scala213_play27
+            - jdk26_scala213_play28
+            - jdk17_scala213_play29
+            - jdk17_scala3_play30
+            - jdk26_scala213_play30
 
       - publish_snapshots_play26_scala211_scala212:
           filters:
